### ISSUE TITLE
Mac OS We're sorry, but something went wrong

### ISSUE THREAD

**Issue by Eschon** [racodond/package-test-sonarqube-css#2]
I tried to get this running on Mac OS X 10.10.5
I went to `sonarqube-5.1.1/bin/macosx-universal-64/`and ran `./sonar.sh start` in the command line everything looked ok so I started my browser and went to http://localhost:9000/ and got the following error:

![screen shot 2015-09-18 at 11 56 10](https://cloud.githubusercontent.com/assets/11647830/9956872/4a5ec424-5dfc-11e5-83b4-c0e7f5403480.png)

**Comment by racodond** [comment]
@Eschon Could you please have a look at the log file at $SONARQUBE_HOME/logs/sonar.log?

**Comment by Eschon** [comment]
Ok I think this is what the log says when I try to access localhost:9000:

```
2015.09.18 11:56:27 ERROR web[o.s.s.ui.JRubyFacade] Fail to render: http://localhost:9000/
"en-US" is not a valid locale
	/Users/egon/.rvm/gems/ruby-2.1.5/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
	/Users/egon/.rvm/gems/ruby-2.1.5/gems/i18n-0.7.0/lib/i18n/config.rb:13:in `locale='
	/Users/egon/.rvm/gems/ruby-2.1.5/gems/i18n-0.7.0/lib/i18n.rb:43:in `locale='
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/app/controllers/application_controller.rb:99:in `set_user_session'
	org/jruby/RubyKernel.java:2223:in `send'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/callbacks.rb:178:in `evaluate_method'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/callbacks.rb:166:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:225:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:629:in `run_before_filters'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:615:in `call_filters'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/core_ext/benchmark.rb:17:in `ms'
	jar:file:/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/1.8/benchmark.rb:308:in `realtime'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/core_ext/benchmark.rb:17:in `ms'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
	org/jruby/RubyKernel.java:2223:in `send'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:532:in `process'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:606:in `process_with_filters'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:391:in `process'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:386:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/routing/route_set.rb:450:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:87:in `dispatch'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:121:in `_call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
	org/jruby/RubyProc.java:290:in `call'
	org/jruby/RubyProc.java:224:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:29:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:9:in `cache'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:28:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/string_coercion.rb:25:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/head.rb:9:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/methodoverride.rb:24:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/params_parser.rb:15:in `call'
	file:/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/session_store.rb:70:in `context'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/session/abstract/id.rb:58:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/failsafe.rb:26:in `call'
	/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:106:in `call'
	file:/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:34:in `serve_rails'
	file:/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:39:in `call'
	file:/Users/egon/Downloads/package-test-sonarqube-css-master/package-test-sonarqube-css/sonarqube-5.1.1/lib/server/jruby-rack-1.1.13.2.jar!/rack/handler/servlet.rb:22:in `call'
```

**Comment by racodond** [comment]
It looks like there's a conflict between some Ruby gems installed on your machine and the SonarQube platform: http://stackoverflow.com/questions/28988441/cant-acess-sonarqube-not-a-valid-locale

**Comment by Eschon** [comment]
Thank you for your help.
Using `rvm use system` did the trick

**Comment by racodond** [comment]
Cool! Have fun with the CSS plugin.

**Comment by adeel-akbar-confiz** [comment]
I have same problem and was fixed with

> rvm use system

Thanks for the help

**Comment by liu3399shuai** [comment]
`2016.07.13 17:21:35 ERROR web[o.s.s.ui.JRubyFacade] Fail to render: http://localhost:9000/
"zh-CN" is not a valid locale
	/Users/liu/.rvm/gems/ruby-2.2.1@global/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
	/Users/liu/.rvm/gems/ruby-2.2.1@global/gems/i18n-0.7.0/lib/i18n/config.rb:13:in `locale='
	/Users/liu/.rvm/gems/ruby-2.2.1@global/gems/i18n-0.7.0/lib/i18n.rb:43:in `locale='
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/app/controllers/application_controller.rb:99:in `set_user_session'
	org/jruby/RubyKernel.java:2223:in `send'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/callbacks.rb:178:in `evaluate_method'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/callbacks.rb:166:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:225:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:629:in `run_before_filters'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:615:in `call_filters'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/core_ext/benchmark.rb:17:in `ms'
	jar:file:/usr/local/Cellar/sonar/5.3/libexec/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/1.8/benchmark.rb:308:in `realtime'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/core_ext/benchmark.rb:17:in `ms'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
	org/jruby/RubyKernel.java:2223:in `send'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:532:in `process'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/filters.rb:606:in `process_with_filters'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:391:in `process'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/base.rb:386:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/routing/route_set.rb:450:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:87:in `dispatch'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:121:in `_call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
	org/jruby/RubyProc.java:290:in `call'
	org/jruby/RubyProc.java:224:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:29:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:9:in `cache'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/query_cache.rb:28:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/config/environment.rb:67:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/string_coercion.rb:25:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/head.rb:9:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/methodoverride.rb:24:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/params_parser.rb:15:in `call'
	file:/usr/local/Cellar/sonar/5.3/libexec/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/session_store.rb:70:in `context'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/rack-1.1.6/lib/rack/session/abstract/id.rb:58:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/failsafe.rb:26:in `call'
	/usr/local/Cellar/sonar/5.3/libexec/web/WEB-INF/gems/gems/actionpack-2.3.15/lib/action_controller/dispatcher.rb:106:in `call'
	file:/usr/local/Cellar/sonar/5.3/libexec/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:34:in `serve_rails'
	file:/usr/local/Cellar/sonar/5.3/libexec/lib/server/jruby-rack-1.1.13.2.jar!/rack/adapter/rails.rb:39:in `call'
	file:/usr/local/Cellar/sonar/5.3/libexec/lib/server/jruby-rack-1.1.13.2.jar!/rack/handler/servlet.rb:22:in `call'

 `

here is my error,help !
